# Change these first
owner: Starstalker-awe # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Inspire My Dreams
    url: https://inspiremydreams.com
  - name: The Karen Yates
    url: https://thekarenyates.com
  - name: Worldschool Camp
    url: https://worldschoolcamp.com
  - name: Background image service
    url: https://imgs.inspiremydreams.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime Monitor
  introTitle: ""
  introMessage: "It's an uptime monitor. The end"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
